#q: WP_013263885.1
#t: 2.A.127.1.6-WP_066273597

qaln = 'QLIKLSVIILLYIAFVVIGMRGSVWRFPLQIEDTFVSNQKLLNDLVPNAIYMLKKACKEKAKAFKVESTDDLLAQYKF-----KSLQEALDVYTDGQIKIAKNDTLTALQHALFAEVGDSLKQPQPNVVIIYSES-WSNYLFNLQQKDAEMNFGLDRHFKEDLLFRNFQSVQNGTINSLENLFVSTPFPHFFTSSYR-------FNTLPTSIALPFKASNYTTMFMSGMDAAWENCAEALPHQQFDAVYDKFFLLKDYPHATYNSIGVYDEYLFQALLDKLN-KPSKKRQMITVMTTTNHPPFEFPKDLKLPPLPDSFYGKKCFAEHNRKVLDKYLTGFRYYNKTLNDFLNRFKASAAAKNTILVITGDHNVRV'
taln = 'QAVPLSMLL---FALLALCARGALGHRPVNPATAAITADHLVNELPLSSLYTVAYAIYQSGKAEEGGITYAEMPQARVIDTVRRETGLPASAFTDPKI------PMRHLQSSLHP------RTRKPNLVIVLEESLGAEFVGRLGGLPLTPN--LDRLAEQGIWFDNLYATGTRSVRGIEAVVAGFP-PTAAVSTVKLAKSQRGFFTLASFL----KPHGYESTFFYGGESHFDNMRSYFMGNGFDRVLEQKDMPKDAFIATW---GASDGDLFERAHQQFSQQPPDKPFFGLVFSSSNHAPFEFPD------------GGFDLYEQPKNTVN---NAVKYADHALGRFFEKARNSAYWDNTIFLVVADHNSRV'

qseq = 'MYKNLTYLLKHSAVILVILFFVRICFAIAFVPMGLIGSNLTVLPRLLFNVLRFDMQVVCYVLLLPTVLTFVFAALRKPWTDRVLSRFRKVYYAIVNILILALSGIDLGFFSNFNSHINLTFFDFFNEGPISLIQAIWEEYHCVYEGLAFLFLSLLILYVIRRIESDKVLARQTNCSLGGRKTSRGQLIKLSVIILLYIAFVVIGMRGSVWRFPLQIEDTFVSNQKLLNDLVPNAIYMLKKACKEKAKAFKVESTDDLLAQYKFKSLQEALDVYTDGQIKIAKNDTLTALQHALFAEVGDSLKQPQPNVVIIYSESWSNYLFNLQQKDAEMNFGLDRHFKEDLLFRNFQSVQNGTINSLENLFVSTPFPHFFTSSYRFNTLPTSIALPFKASNYTTMFMSGMDAAWENCAEALPHQQFDAVYDKFFLLKDYPHATYNSIGVYDEYLFQALLDKLNKPSKKRQMITVMTTTNHPPFEFPKDLKLPPLPDSFYGKKCFAEHNRKVLDKYLTGFRYYNKTLNDFLNRFKASAAAKNTILVITGDHNVRVILNNDVIDKRYEHSVPLYVYLPPYLRKEAYNKLTNRWGSHDDILATVAPFAFRNTKYFKMGKNLLDTSVSDSTYYSANVDQIEAIPSYQNKAERLTAARNLLRQVYFGLYWRTQQ'
tseq = 'MHALPSARPGALLVTPARPHPLTAWSGLFGLLAFVLLWDLSGLDMVVMQHIGTAQGFALQDHWWLSHVLHDGLRQAMVGAWLLLGAWTLWPRSALPRRERALVWGLATLSLLAVNLVKNHSLTSCPWDLQAFGGSAQTVSHWAWGLSDGGPGRCFPGGHASSGFAFIALCLPWLDAPAGRIRRREVGWRWLIAVLAVGGLAGAVQTLRGAHFPSHNLWTLWICCAVSLAGWRLMRARPAVPAASSDATRRPRLPWRNTLAVLRPLLVPMACMLVLLWLSRLGLALWQHERISQAQAWPLLWQQGLRFDAVLIGLVWAAPAALTPWMAMARPTQRAWSAALRWYGGLALLLLAFMELSTPAFIAQYDSRPNYLFVEYLGYAKEVGGTLLKDYWAHLLAAAVALPAMAWAYVRASRPATRPATPLCVWQAVPLSMLLFALLALCARGALGHRPVNPATAAITADHLVNELPLSSLYTVAYAIYQSGKAEEGGITYAEMPQARVIDTVRRETGLPASAFTDPKIPMRHLQSSLHPRTRKPNLVIVLEESLGAEFVGRLGGLPLTPNLDRLAEQGIWFDNLYATGTRSVRGIEAVVAGFPPTAAVSTVKLAKSQRGFFTLASFLKPHGYESTFFYGGESHFDNMRSYFMGNGFDRVLEQKDMPKDAFIATWGASDGDLFERAHQQFSQQPPDKPFFGLVFSSSNHAPFEFPDGGFDLYEQPKNTVNNAVKYADHALGRFFEKARNSAYWDNTIFLVVADHNSRVYGPSLIPVERFHIPGLILGGPIQQPQRINTVASQIDLAPTLVSLMGLSGEQPWIGRDMSDPAQRVRPGRAILQFDKIQAYMEGDRLAVLQPDSPPRLMRYHDGVLKDTQQPDPALVETAQAHARYAQWAYQRQWHR'

qGaps = qaln.count("-") #14 gaps
tgaps = taln.count("-") #40 gaps

qTMS = [[12, 36], [57, 75], [92, 111], [142, 160], [187, 205]] #[187,205] within aligned region
tTMS = [[22, 41], [72, 90], [103, 123], [154, 174], [187, 204], [217, 234], [265, 285], [310, 329], [342, 362], [393, 410], [423, 441]] #[423,441] within aligned region

qalnClean = qaln.replace("-", "")
qalnStartPos = qseq.find(qalnClean)#185
qalnEndPos = qalnStartPos + len(qalnClean)#545

talnClean = taln.replace("-", "")
talnStartPos = tseq.find(talnClean)#426
talnEndPos = talnStartPos + len(talnClean)#760

overlaps = 0
#Minimum Residue Number for an overlap to be counted
minRes = 8
#filtering out TMS that are completely outside aligned regions
for i in (i for i in qTMS if not i[0] > qalnEndPos and not i[1] < qalnStartPos): 
    print(i)
    tempQString = qseq[i[0]:i[1]]
    # starting position of TMS out of aligment range
    if i[0] < qalnStartPos:
        tempQString = qseq[qalnStartPos:i[1]]

        #starting and ending positions of TMS both out of alignment range
        if i[1] > qalnEndPos:
            tempQString = qseq[qalnStartPos:qalnEndPos]
    
    # ending position of TMS out of alignment range
    elif i[1] > qalnEndPos:
        tempQString = qseq[i[0]:qalnEndPos]

    #At this Point, tempQString is finalized
    print(tempQString)

    for j in (j for j in tTMS if not j[0] > talnEndPos and not j[1] < talnStartPos):
        sameRes = 0
        print(j)
        tempTString = tseq[j[0]:j[1]]
        # starting position of TMS out of alignment range
        if j[0] < talnStartPos:
            tempTString = tseq[talnStartPos:j[1]]

            #starting and ending positions of TMS both out of alignment range
            if j[1] > talnEndPos:
                tempTString = tseq[talnStartPos:talnEndPos]

        #ending position of TMS out of alignment range
        elif j[1] > talnEndPos:
            tempTString = tseq[j[0]:talnEndPos]
        
        #At this point, tempTString is finalized
        print(tempTString)
        
        for loc in range (0, len(tempQString)) :
            if (loc < len(tempTString)):
                if tempQString[loc] == tempTString[loc]:
                    sameRes += 1
        
        print(sameRes)
        if sameRes >= minRes:
            overlaps += 1

        

